Repository wasteofplus/wasteof.plus, pull requests merged in 2023-08, with the labels that each got.

#52 Make Build Scripts compatible with Windows
  package-lock.json
  package.json
Labels: bug, dependencies

#81 Fixed bug in hashtags addon.
  CONTRIBUTING.md
  addons/hashtags/addon.js
Labels: bug

#84 Add large extension icons to README
  README.md
Labels: style

#95 Add @TheAwesome98-Real Zap Sound Effect for New Messages
  addons/addMessageCountBadge/addon.json
  assets/sounds/wasteof_notification.wav
  background/background.js
  popups/popup.js
Labels: feature

#122 Fix glitch where polls icon is added multiple times
  addons/polls/addon.js
Labels: bug
