Repository wasteofplus/wasteof.plus, pull requests merged in 2023-07, with the labels that each got.

#9 New Addon: profileHoverCards
  addons/profileHoverCards/addon.css
  addons/profileHoverCards/addon.js
  addons/profileHoverCards/addon.json
  addons/profileHoverCards/lib/getToken.js
  addons/profileHoverCards/templates/hovercard4.html
  background/background.js
  manifest.json
  utils.js
Labels: enhancement

#15 Fix bug with hovercard follow button not hiding for signed out users
  addons/profileHoverCards/addon.js
Labels: bug

#17 Add ESLint formatting
  .eslintrc.js
  addons/addUserStatuses/addon.js
  package-lock.json
  package.json
  utils.js
Labels: enhancement

#27 Implement chat presence notification
  addons/addons.json
  addons/chatPresenceNotify/addon.css
  addons/chatPresenceNotify/addon.js
  addons/chatPresenceNotify/addon.json
  addons/chatPresenceNotify/lib/notify.js
  background/background.js
  manifest_firefox.json
Labels: new addon

#33 Polls
  addons/addons.json
  addons/polls/addon.css
  addons/polls/addon.js
  addons/polls/addon.json
Labels: new addon

#56 Possible Fix for the Hovercard bug
  addons/profileHoverCards/addon.js
Labels: bug
